# Generated by Django 5.2.4 on 2025-08-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='subject identifier'),
        ),
    ]
