# Generated by Django 5.2.4 on 2025-09-05 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(help_text='保存先のGCSバケット名', max_length=255)),
                ('name', models.CharField(help_text='GCSオブジェクトのパス', max_length=1024)),
                ('size', models.BigIntegerField(help_text='ファイルサイズ (バイト)')),
                ('content_type', models.CharField(help_text='MIMEタイプ (例: image/jpeg)', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(help_text='この写真を所有するユーザー', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
