# Generated by Django 5.2.4 on 2025-09-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='gcs_path',
        ),
        migrations.AddField(
            model_name='photo',
            name='content_type',
            field=models.CharField(default='image/jpeg', max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
