# Generated by Django 5.2.4 on 2025-09-21 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_alter_photo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='photo',
            name='gcs_path',
            field=models.CharField(default='', help_text='GCSオブジェクトのフルパス (例: gs://bucket/name)', max_length=1024),
        ),
        migrations.AlterField(
            model_name='photo',
            name='content_type',
            field=models.CharField(default='image/jpeg', help_text='MIMEタイプ (例: image/jpeg)', max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='owner',
            field=models.ForeignKey(help_text='この写真を所有するユーザー', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='size',
            field=models.BigIntegerField(default=0, help_text='ファイルサイズ (バイト)'),
        ),
    ]
