# Generated by Django 5.2.4 on 2025-09-21 03:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='gcs_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=128, unique=True),
        ),
    ]
